name: Simple Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix-shell -p curl --run 'curl -s ifconfig.me > ip.txt'
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: ip.txt
